name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      - name: Load Environment Variables
        run: |
          cat .env >> $GITHUB_ENV
          
      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Sparse Checkout Linux Kernel Source
        run: |
          rm -rf src
          mkdir -p src
          cd src
          git init
          git remote add origin "$KERNEL_REPO"
          git config core.sparseCheckout true
          git sparse-checkout set $KERNEL_SPARSE_DIRS 
          git fetch --filter=blob:none --depth=1 origin tag "$KERNEL_TAG" 
          git checkout FETCH_HEAD
          cd ..
        # unquoted $KERNEL_SPARSE_DIRS: folder names passed as separate arguments to git sparse-checkout set.
          
      - name: Build Doxygen Documentation
        run: |
          chmod +x ./doxygen_kernel_filter.sh
          chmod +x generate_flags.py
          python3 generate_flags.py
          rm -rf html/          
          doxygen Doxyfile          
          touch ./html/.nojekyll

      - name: Upload artifact
        if: ${{ !env.ACT }}
        # Only upload artifacts on GitHub actions, skip in local act
        uses: actions/upload-pages-artifact@v3
        with:
          path: './html'

      - name: Deploy to GitHub Pages
        # only deploy on GitHub actions, not locally
        if: ${{ !env.ACT }} 
        id: deployment
        uses: actions/deploy-pages@v4